[package]
name = "handheld-halting"
version = "0.1.0"
authors = ["Jean SIMARD <woshilapin@tuziwo.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
